const print = console.log;
print();
print("Hello and welcome to the course!");
print("We seem to be using");
print("a lots of prints here.");
print("Why don't we rename it");
print("to make it look better ?");
print("To do that, simply assign the function");
print("'print' to another variable.");
print("you can call it whatever you want.");
print("I called mine 'line' to reflect the");
print("way that I'm using it.");
